controllers/OpdController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Ovst;
use app\models\OvstSearch;
use app\models\Ptinfo;
use app\models\Pttype;
use yii\web\Controller;

use app\models\Pi;
use app\models\Pe;
use app\models\Symptm;
use app\models\Ph;
use app\models\Clinic;
use app\models\Labresult;
use app\models\Visitadvice;
use app\models\Ovstdx;
use app\models\Oprt;
use app\models\Prsc;
use app\models\Prscdt;
use app\models\Lbbk;
use app\models\Xryrqt;
use app\models\Oapp;
use app\models\Ovstost;
use app\models\Orfro;
use app\models\Reserv;
use app\models\Visitnoteconsult;
use app\models\LCr;
use app\models\Lbuncr;
use app\models\PtAllergy;
use app\models\Reciept;
use app\models\RepTotal;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;
use yii\filters\AccessControl;
use yii\i18n\Formatter;

/**
 * OpdController implements the CRUD actions for Ovst model.
 */
class OpdController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Ovst models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OvstSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Ovst models.
     * @return mixed
     */
    public function actionRep($id)
    {
        $model = $this->findModel($id);
        $ptinfo = Ptinfo::findOne($model->hn);
        $pttype = Pttype::findOne($model->pttype);
        $rep = RepTotal::findOne($id);
        $paid = Reciept::findOne($id);
        $total = number_format($rep->total - $paid->total,2);
        
        $content = $this->renderPartial('_print_rep',[
            'model' => $model,
            'ptinfo' => $ptinfo,
            'pttype' => $pttype,
            'total' => $total,
        ]);

        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            // A4 paper format
            'format' => Pdf::FORMAT_A4,
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            'cssFile' => '@app/web/css/pdf.css',
            // any css to be embedded if required
            'cssInline' => '.bd{border:1.5px solid; text-align: center;} .ar{text-align:right} .imgbd{border:1px solid}',
            // set mPDF properties on the fly
            'options' => ['title' => 'ใบติดตามหนี้'],
            // call mPDF methods on the fly
            'methods' => [
                //'SetHeader'=>[''],
                //'SetFooter'=>['{PAGENO}'],
            ]
        ]);

        return $pdf->render();

    }

    /**
     * Displays a single Ovst model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Ovst model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Ovst();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->vn]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Ovst model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->vn]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Ovst model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionPrint($id)
    {
        $model = $this->findModel($id);
        $ptinfo = Ptinfo::findOne($model->hn);
        $pttype = Pttype::findOne($model->pttype);

        $cc = Symptm::find()->where(['vn' =>$model->vn])->one();
        $pi = Pi::findOne($model->vn);
        $pe = Pe::findOne($model->vn);
        $ph = Ph::findOne($model->vn);
        $clinic = Clinic::findOne($model->cln);
        $advice = Visitadvice::find()->where(['vn' => $model->vn])->one();
        $diag = Ovstdx::find()->where(['vn' => $model->vn])->orderBy('id')->all();
        $proc = Oprt::find()->where(['vn' => $model->vn])->orderBy('id')->all();
        $prsc = Prsc::find()->where(['vn' => $model->vn])->one();
        $rx = Prscdt::find()->where(['prscno' => $prsc->prscno])->all();
        $lab = Lbbk::find()->where(['vn' => $model->vn])->all();
        $xry = Xryrqt::find()->where(['vn' => $model->vn])->all();
        $appoint = Oapp::find()->where(['vn' => $model->vn])->all();
        $out = Ovstost::find()->where(['ovstost' => $model->ovstost])->one();
        $refer = Orfro::find()->where(['vn' => $model->vn])->one();
        $consult = Visitnoteconsult::find()->where(['vn' => $model->vn])->one();
        $cr = LCr::findOne($model->hn);
        $labresult = Labresult::find()->where(['ln' => $cr->last_ln])->all();

        $content = $this->renderPartial('_print',[
            'model' => $model,
            'ptinfo' => $ptinfo,
            'pttype' => $pttype,
            'cc' => $cc,
            'pi' => $pi,
            'pe' => $pe,
            'ph' => $ph,
            'clinic' => $clinic,
            'advice' => $advice,
            'diag' => $diag,
            'proc' => $proc,
            'rx' => $rx,
            'lab' => $lab,
            'xry' => $xry,
            'appoint' => $appoint,
            'out' => $out,
            'refer' => $refer,
            'consult' => $consult,
            'cr' => $cr,
            'labresult' => $labresult,
        ]);
        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            // A4 paper format
            'format' => Pdf::FORMAT_A4,
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            'cssFile' => '@app/web/css/pdf.css',
            // any css to be embedded if required
            'cssInline' => '.bd{border:1.5px solid; text-align: center;} .ar{text-align:right} .imgbd{border:1px solid}',
            // set mPDF properties on the fly
            'options' => ['title' => 'OPD CARD : '.$id],
            // call mPDF methods on the fly
            'methods' => [
                //'SetHeader'=>[''],
                //'SetFooter'=>['{PAGENO}'],
            ]
        ]);

        return $pdf->render();

    }

    public function actionNcd($id)
    {
        $model = $this->findModel($id);
        $ptinfo = Ptinfo::findOne($model->hn);
        $pttype = Pttype::findOne($model->pttype);

        $cc = Symptm::find()->where(['vn' =>$model->vn])->one();
        $pi = Pi::findOne($model->vn);
        $pe = Pe::findOne($model->vn);
        $ph = Ph::findOne($model->vn);
        $clinic = Clinic::findOne($model->cln);
        $advice = Visitadvice::find()->where(['vn' => $model->vn])->one();
        $diag = Ovstdx::find()->where(['vn' => $model->vn])->orderBy('id')->all();
        $proc = Oprt::find()->where(['vn' => $model->vn])->orderBy('id')->all();
        $prsc = Prsc::find()->where(['vn' => $model->vn])->one();
        $rx = Prscdt::find()->where(['prscno' => $prsc->prscno])->all();
        $lab = Lbbk::find()->where(['vn' => $model->vn])->all();
        $xry = Xryrqt::find()->where(['vn' => $model->vn])->all();
        $appoint = Oapp::find()->where(['vn' => $model->vn])->all();
        $out = Ovstost::find()->where(['ovstost' => $model->ovstost])->one();
        $refer = Orfro::find()->where(['vn' => $model->vn])->one();
        $consult = Visitnoteconsult::find()->where(['vn' => $model->vn])->one();
        $cr = LCr::findOne($model->hn);
        $labresult = Labresult::find()->where(['ln' => $cr->last_ln])->all();
        $allergy = PtAllergy::find()->where(['hn'=>$model->hn])->one();

        $content = $this->renderPartial('_print_ncd',[
            'model' => $model,
            'ptinfo' => $ptinfo,
            'pttype' => $pttype,
            'cc' => $cc,
            'pi' => $pi,
            'pe' => $pe,

views/opd/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Ovst */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="ovst-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'vstdttm')->textInput() ?>

    <?= $form->field($model, 'hn')->textInput() ?>

    <?= $form->field($model, 'cln')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'dct')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'pttype')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'sickdate')->textInput() ?>

    <?= $form->field($model, 'ovstist')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'ovstost')->textInput() ?>

    <?= $form->field($model, 'bw')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'height')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tt')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'pr')->textInput() ?>

    <?= $form->field($model, 'rr')->textInput() ?>

    <?= $form->field($model, 'sbp')->textInput() ?>

    <?= $form->field($model, 'dbp')->textInput() ?>

    <?= $form->field($model, 'an')->textInput() ?>

    <?= $form->field($model, 'register')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'waist_cm')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/opd/_print.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\Meditem;
use app\models\Lab;
use app\models\Xray;
use app\models\Clinic;
use app\models\Hospcode;
use app\models\Dct;
use app\models\Lcbc;
use app\models\Lelyte;
use app\models\LCr;
use app\models\Ldtx;
use app\models\Medusage;

$birthdate = new DateTime($ptinfo->birth);
$visit = new DateTime($model->vstdttm);
$visit_date = date_format($visit,'d/m/Y');
$visit_time = date_format($visit,'H:i');

function age($bdate,$vdate){
  $difference = $bdate->diff($vdate); 
  
  $age = $difference->format('%y');  
  return $age;
} 

function egfr($age,$creat,$sex){
  if ($creat){
    if($sex == '1'){
      if($creat > 0.9) {
        $egfr = 141  * pow(0.993,$age) / pow(($creat/0.9),1.209);
      } else {
        $egfr = 141  * pow(0.993,$age) / pow(($creat/0.9),0.411);
      }
    } else {
      if($creat > 0.9) {
        $egfr = 144  * pow(0.993,$age) / pow(($creat/0.7),1.209);
      } else {
        $egfr = 144  * pow(0.993,$age) / pow(($creat/0.7),0.329);
      }
    }  
  } else {
    $egfr = 'NA';
  }
  return round($egfr,2);
}

?>
  <h2 align="center">ประวัติการรักษาผู้ป่วยนอก OPD CARD</h2>
  <h3 align="center">โรงพยาบาลเหล่าเสือโก้ก อำเภอเหล่าเสือโก้ก จังหวัดอุบลราชธานี</h3>
<p>
   ชื่อ : <?php echo $ptinfo->prename.$ptinfo->ptname; ?> เพศ :<?php echo $ptinfo->sex;?> 
   อายุ : <?php echo age($birthdate,$visit); ?> ปี HN :<?php echo $model->hn; ?> เลขบัตรประชาชน :<?php echo $ptinfo->cid;?>
   สิทธิ์ : <?php echo $pttype->namepttype; ?><br>
   รับบริการวันที่ <?php echo $visit_date; ?> เวลา <?php echo $visit_time; ?> น. 
   แผนก <?php echo $clinic->namecln; ?>
</p>
<p><b>Vitaul Sign</b>
  BT : <?php echo $model->tt; ?> ºC, BP : <?php echo $model->sbp.'/'.$model->dbp; ?> mmHg, PR : <?php echo $model->pr?> /m, RR <?php echo $model->rr?> /m,
  BW : <?php echo $model->bw; ?> kg, ส่วนสูง :<?php echo $model->height?> cm, BMI :<?php if($model->height <> 0) { echo round(($model->bw)/(($model->height/100)*($model->height/100)),2);} ?> 
</p>
<p>
<table>
  <tr>
    <td width=40%  valign="top">
      <b>Chief Compaint :</b> <?php echo $cc->symptom; ?>
    </td>
    <td rowspan="2" colspan="4"  valign="top">
      <b>Diagnosis :</b> <br>
      <?php 
        foreach($diag as $dx){
          echo $dx->icd10.'=>'.$dx->icd10name."<br>";
        }
      ?> 
    </td>
  </tr>
  <tr>
    <td valign="top">
      <b>Present Illness :</b> <?php echo $pi->pi; ?>      
    </td>
  </tr>
  <tr>
    <td rowspan="2" valign="top">
      <b>Past History : </b><?php echo $ph->ph; ?>    
    </td>
    <td colspan="4" valign="top">
      <b>Laboratory :</b> 
    <?php
      foreach($lab as $r){
        if($r->labcode == '222'){
          $creat = LCr::find()->where(['last_ln' => $r->ln])->one();
        }
        if($r->labcode == '001'){
          $cbc = Lcbc::find()->where(['ln' => $r->ln])->one();
        }
        if($r->labcode == '031'){
          $elyte = Lelyte::find()->where(['ln' => $r->ln])->one();
        }
        if($r->labcode == '306'){
          $dtx = Ldtx::find()->where(['ln' => $r->ln])->one();
        }

        $l = Lab::findOne($r->labcode);
        echo $l->labname.',';
      }
    ?>
    </td>
  </tr>
  <tr>
  <td colspan=2 valign="top"><b>ผลการชันสูตรที่สำคัญ</b>
      <br>
      <?php 
      if($labresult){
        echo 'Creatinine: '.$labresult->labresult.' mg/dL '.'<br>&emsp;';
        echo 'eGFR(CKD-EPI): '.egfr($cr->age,$labresult->labresult,$cr->sex).' mL/min/1.73^2 <br>&emsp;' ;
      }  
      if($dtx){
        echo 'DTX: '.$dtx->dtx; 
      }
      ?> 
    </td>
    <td valign="top" style="background-image:url(../web/imgs/cbc.jpg);background-repeat:no-repeat;background-size:160px 100px;   width: 160px; height: 100px;">
      <?php if($cbc){echo 'CBC : '?><br><br>&emsp;<?php echo $cbc->hb;?>&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; <?php echo $cbc->pmn; ?>
      <br> &emsp; &emsp; &emsp; &emsp;&emsp;<?php echo $cbc->wbc; ?> <br>&emsp;
      <br> &emsp; &emsp; &emsp; &emsp; <?php echo $cbc->pltc; ?> <br>&emsp;       
      <br> &emsp; <?php echo $cbc->hct;?>&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; <?php echo $cbc->lym;} ?>
    </td>
    <td valign="top" style="background-image:url(../web/imgs/elyte.jpg);background-repeat:no-repeat;background-size:160px 100px;   width: 160px; height: 100px;">
      <?php if($elyte){echo 'Elyte : '?> <br><br>&emsp;&emsp; &emsp;
      <?php echo $elyte->na;?>&emsp; &emsp; <?php echo $elyte->k; ?>
      <br> &emsp;<br> &emsp;<br>&emsp;&emsp; &emsp; 
      <?php echo $elyte->cl;?>&emsp; &emsp; <?php echo $elyte->co2; }?></td>
  </tr>
  <tr>
    <td rowspan="2" valign="top">
      <b>Physical Exam :</b> <br><br>
      <img width=200 align="center" src="../web/imgs/imgpe.jpg">      
      <p><?php echo $pe->pe ?></p>    
    </td>
    <td colspan="4" valign="top">
      </b>X-Ray : </b> 
      <?php
        foreach($xry as $r){
          $l = Xray::findOne($r->xrycode);
          echo $l->xryname.',';
        }
      ?>    
    </td>
  </tr>
  <tr>
    <td colspan="4" valign="top">
    <table>
    <tr>
      <td width=40%><b>Rx : ชื่อยา</b></td>
      <td width=40%><b>วิธีใช้</b></td>
      <td width=10%><b>จำนวน</b></td>
      <td width=10%><b>ED/NED</b></td>
    </tr>
    <?php
      foreach($rx as $r){
        $unit = Meditem::findOne($r->meditem);
        if($unit->ed ==1){
          $ed = 'ED';
        } else {
          $ed = 'NED';
        }
        $use = Medusage::find()->where(['dosecode' => $r->medusage])->one();
        echo '<tr><td>'.$r->nameprscdt.'</td><td>'. $use->doseprn1.' '.$use->doseprn2.'</td><td>'.$r->qty.' '.$unit->pres_unt.'</td><td>'.$ed.'</td></tr>';
      }
    ?>
    </table>
    </td>
  </tr>
  <tr>
    <td>
      <b>Consult : /<b><?php echo $consult->detail; ?>
    </td>
    <td colspan="4">
      <b>นัด : </b>    
    <?php
      foreach($appoint as $r){
        $c = Clinic::find()->where('substr(cln,1,1) = :cln',[':cln' => substr($r->cln,0,1)])->one();
        $fd = new DateTime($r->fudate);
        echo $c->namecln.':'.$r->dscrptn.' วันที่ '.date_format($fd,'d/m/Y').'<br>';
      }
    ?>
    </td>  
  </tr>    
  <tr>
    <td valign="top">
      <b>Procedure : </b> 
    <?php
      foreach($proc as $pr){
        echo $pr->icd9cm.'=>'.$pr->icd9name.',';
      }
    ?>
    </td>
    <td rowspan="3" colspan="4" valign="top">
      <b>คำแนะนำ : </b><?php echo $advice->advice; ?>
    </td>
  </tr>
  <tr>
    <td valign="top">
      <b>แพทย์ผู้รักษา </b> 
    <?php 
      if(strlen($model->dct) == 5 ){
        $doctor = Dct::find()->where(['lcno' => $model->dct])->one();
      } else {
        $doctor = Dct::find()->where(['dct' => substr($model->dct,2,2)])->one();
      }
      echo $doctor->fname.' '. $doctor->lname .'<br> เลขที่ใบประกอบวิชาชีพ :'.$doctor->lcno;
    ?>
    </td>
  </tr>
  <tr>
    <td valign="top">
      <b>สถานะจำหน่าย : </b> 
    <?php 
      if($model->ovstost == 1){
        echo "กลับบ้าน";
      } else if($model->ovstost == 2){
        echo "เสียชีวิต";
      } else if($model->ovstost == 4){
        echo "รับรักษาในโรงพยาบาล AN:" . $model->an;
      } else if($model->ovstost == 3){
        $h = Hospcode::find()->where(['off_id' =>$refer->rfrlct])->one();
      echo "ส่งต่อ :".$h->namehosp;
      }
    ?> 
    </td>
  </tr>
</table>
</p>

views/opd/_print_vacc.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\Ptinfo;


function age($bdate){
  $visit_date = date("Y-m-d");
  $vdate = new DateTime($visit_date);
  $difference = $bdate->diff($vdate); 
  $age = $difference->format('%y');  
  return $age;
} 
$i = 1;
foreach ($model as $visit) {
  $ptinfo = Ptinfo::findOne($visit->hn);
  $birthdate = new DateTime($ptinfo->birth);
?>
<font size="5">
  <b>ลำดับที่ : <?= $i ?> HN : <?php echo $visit->hn; ?></b> ชื่อ : <?php echo $ptinfo->prename.$ptinfo->ptname; ?> เพศ : <?php echo $ptinfo->sex;?> อายุ : <?php echo age($birthdate,$v); ?> ปี เลขบัตรประชาชน : <?php echo $ptinfo->cid;?> <br>
  V/S BW <u>&emsp; &emsp; </u> kg สูง <u>&emsp; &emsp; </u> ซม. รอบเอว <u>&emsp; &emsp; </u> นิ้ว BT <u>&emsp; &emsp; </u> C PR <u>&emsp; &emsp; </u> RR <u>&emsp; &emsp; </u> BP1 <u>&emsp; &emsp; / &emsp; &emsp; </u> BP2 <u>&emsp; &emsp; / &emsp; &emsp; </u> <br>
  ฉีดวัคซีนเวลา <u>&emsp; &emsp; &emsp; </u> น. สังเกตุอาการ 30 นาที ถึง <u>&emsp; &emsp; &emsp; </u> น. 
  ก่อนจำหน่าย BP <u>&emsp; &emsp; / &emsp; &emsp; </u> &emsp;[&emsp;] กลับบ้าน [&emsp;] refer<br>
  อาการผิดปกติ <u>&emsp;&emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </u><br>
  <u>&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </u>
  </font>
  <br><br>
  <br>
<hr>
<?php
$i++; 
}
echo "<pagebreak>";
$i = 1;
echo '<table calss="table_bordered" width="100%" border="1" cellpadding="2" cellspacing="0"><tr><th width="50">ลำดับที่</th><th width="80">HN</th><th>ชื่อ-สกุล</th><th width="200"> หมายเหตุ </th></tr>';
foreach ($model as $visit) {
  $ptinfo = Ptinfo::findOne($visit->hn);
  echo '<tr><td align="right"><font size="5">'. $i.'&emsp;</font></td><td align="right"><font size="5">'. $visit->hn .'&emsp;</font></td><td><font size="5">&emsp;'.$ptinfo->prename.$ptinfo->ptname."</font></td><td> &ensp;[ &emsp;] รับเอกสารแล้ว </td></tr>";
$i++;
}
echo "</table>";
?>

views/opd/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\OvstSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="ovst-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'hn') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/opd/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\OvstSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Ovsts';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ovst-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php echo $this->render('_search', ['model' => $searchModel]); ?>
    <?= Html::a('พิมพ์ ใบนำทาง Vaccine', ['vacc'], ['class' => 'btn btn-primary']) ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        // 'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'vstdttm',
            'hn',
            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'buttonOptions'=>['class'=>'btn btn-primary'],
                'template'=>'{print}',
                'buttons'=>[
                    'print' => function($url,$model,$key){
                      return Html::a('Print',['opd/print','id'=>$model->vn],['class' => 'btn btn-primary','target'=>'_blank']);
                    }
                ]
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'buttonOptions'=>['class'=>'btn btn-primary'],
                'template'=>'{ncd}',
                'buttons'=>[
                    'ncd' => function($url,$model,$key){
                      return Html::a('ใบแนบสมุด',['opd/ncd','id'=>$model->vn],['class' => 'btn btn-primary','target'=>'_blank']);
                    }
                ]
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'buttonOptions'=>['class'=>'btn btn-primary'],
                'template'=>'{rep}',
                'buttons'=>[
                    'rep' => function($url,$model,$key){
                        $pttype = ['10','11','12','13','14','21','22','23','37','70'];
                        if(in_array($model->pttype,$pttype)){
                            return Html::a('ใบทวงหนี้',['opd/rep','id'=>$model->vn],['class' => 'btn btn-warning','target'=>'_blank']);
                        }
                    }
                ]
            ],
        ],

    ]); ?>


</div>