controllers/IpdController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Ipt;
use app\models\Cbc;
use app\models\Elyte;
use app\models\Dc;
use app\models\DcSearch;
use app\models\IptSearch;
use app\models\ListIpd;
use app\models\ListIpdSearch;
use app\models\ListPrsc;
use app\models\ListPrscSearch;
use app\models\ListLab;
use app\models\Labresult;
use app\models\LCr;
use app\models\Lcbc;
use app\models\Lelyte;
use app\models\Lbuncr;
use app\models\ViewDtx;
use app\models\ViewDtxSearch;
use app\models\Diag;
use app\models\IpdPe;
use app\models\Lbbk;
use app\models\Proc;
use app\models\NurseNote;
use app\models\DoctorOrder;
use app\models\PtAllergy;
use app\models\Ptinfo;
use app\models\Viewfood;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;
use yii\filters\AccessControl;

//use yii\data\SqlDataProvider;

/**
 * IpdController implements the CRUD actions for Ipt model.
 */
class IpdController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Ipt models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ListIpdSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->orderBy(['an'=>SORT_DESC]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Ipt models.
     * @return mixed
     */
    public function actionDc()
    {
        $searchModel = new DcSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->orderBy(['an'=>SORT_DESC]);

        return $this->render('index_dc', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    /**
     * Displays a single Ipt model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionFood()
    {
        $model = Viewfood::find()->all();

        $content = $this->renderPartial('_food',[
            'model' => $model,
        ]);

        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            // A4 paper format
            'format' => Pdf::FORMAT_A4,
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            'cssFile' => '@app/web/css/pdf.css',
            // any css to be embedded if required
            'cssInline' => '.bd{border:1.5px solid; text-align: center;} .ar{text-align:right} .imgbd{border:1px solid}',
            // set mPDF properties on the fly
            'options' => ['title' => 'ใบเบิกอาหาร '],
            // call mPDF methods on the fly
            'methods' => [
                //'SetHeader'=>[''],
                //'SetFooter'=>['{PAGENO}'],
            ]
        ]);

        return $pdf->render();

    }

    /**
     * Creates a new Ipt model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Ipt();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->an]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Ipt model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->an]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Ipt model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Ipt model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Ipt the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ListIpd::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionPrint($id)
    {
        $model = $this->findModel($id);
        $ptinfo = Ptinfo::find()->where(['hn'=>$model->hn])->one();
        $allergy = PtAllergy::find()->where(['hn'=>$model->hn])->one();
        $lablist = Lbbk::find()->where(['an'=>$model->an])->all();
        $cbc = Cbc::find()->where(['an' => $model->an])->one();
        $elyte = Elyte::find()->where(['an' => $model->an])->one();
        $cr = LCr::findOne($model->hn);
        $creat = new Labresult();
        $nr = NurseNote::find()->where(['an'=>$model->an])->all();
        $doctor_order = DoctorOrder::find()->where(['an'=>$model->an])->all();
        
        if($cr){
            $creat = Labresult::find()->where(['ln' =>$cr->last_ln])->one();
        }

        $content = $this->renderPartial('_print',[
            'model' => $model,
            'cbc' => $cbc,
            'elyte' => $elyte,
            'cr'=> $cr,
            'creat'=> $creat,
            'lablist' => $lablist,
            'nr' => $nr,
            'doctor_order' => $doctor_order,
            'allergy' => $allergy,
            'ptinfo' => $ptinfo,
        ]);
        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            // A4 paper format
            'format' => Pdf::FORMAT_A4,
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            'cssFile' => '@app/web/css/pdf.css',
            // any css to be embedded if required
            'cssInline' => '.bd{border:1.5px solid; text-align: center;} .ar{text-align:right} .imgbd{border:1px solid}',
            // set mPDF properties on the fly
            'options' => ['title' => 'Admission Note : '.$id],
            // call mPDF methods on the fly
            'methods' => [
                //'SetHeader'=>[''],
                'SetFooter'=>['<h6 align="right">ปรับปรุงเมื่อวันที่ 30 ธ.ค. 2564</h6>'],
            ]
        ]);

        return $pdf->render();

    }

    public function actionDcprint($id)
    {
        $model = Dc::findOne($id);

        $diag = new Diag;
        $diag = Diag::findOne($id);

        $proc = new Proc;
        $proc = Proc::findOne($id);

        $ipd_pe = new IpdPe;
        $ipd_pe = IpdPe::findOne($id);

        $lablist = new ListLab;
        $lablist = ListLab::findOne($id);

        $fcbc = new Cbc;
        $lcbc = new Cbc;

        $felyte = new Elyte;
        $lelyte = new Elyte;

        $fcreat = new Labresult;
        $lcreat = new Labresult;

        $dtxSearch = new ViewDtxSearch;
        $dtx = $dtxSearch->search(Yii::$app->request->queryParams);
        $dtx->query->where(['an'=>$id]);

        if($lablist) {
            if($lablist->fcbc){
                if($lablist->fcbc <> $lablist->lcbc) {
                    $fcbc->ln = $lablist->fcbc;
                    $fcbc->hb = Labresult:: find()->where(['ln' => $lablist->fcbc , 'lab_code_local' => 'Hb'])->one();
                    $fcbc->hct = Labresult:: find()->where(['ln' => $lablist->fcbc , 'lab_code_local' => 'Hct'])->one();
                    $fcbc->pltc = Labresult:: find()->where(['ln' => $lablist->fcbc , 'lab_code_local' => 'Pltc'])->one();
                    $fcbc->pmn = Labresult:: find()->where(['ln' => $lablist->fcbc , 'lab_code_local' => 'Pmn'])->one();
                    $fcbc->lym = Labresult:: find()->where(['ln' => $lablist->fcbc , 'lab_code_local' => 'Lym'])->one();
                    $lcbc->ln = $lablist->lcbc;
                    $lcbc->hb = Labresult:: find()->where(['ln' => $lablist->lcbc , 'lab_code_local' => 'Hb'])->one();
                    $lcbc->hct = Labresult:: find()->where(['ln' => $lablist->lcbc , 'lab_code_local' => 'Hct'])->one();

views/ipd/_food.php
<?php 
use app\models\Calendar;

$d = Calendar::find()->all();

foreach ($d as $i){
?>

<h2 align="center">ใบเบิกอาหารตามตึกผู้ป่วย</h2>
<h3 align="center">ฝ่ายโภชนาการโรงพยาบาลเหล่าเสือโก้ก ตึกผู้ป่วยใน 
    <br>วันที่ <?= $i->getDateorder() ?> มิถุนายน พ.ศ. 2564 เวลา ........... น.
</h3>

<table calss="table_bordered" width="100%" border="1" cellpadding="2" cellspacing="0">
<tr>
<th>เตียง</th>
<th>ชื่อ-สกุล</th>
<th>อายุ</th>
<th>อาหารหลัก</th>
<th>อาหารรอง</th>
<th>FEED</th>
<th>CC</th>
<th>ไข่ขาว/มื้อ</th>
<th>หมายเหตุ</th>
</tr>
<?php 
 foreach ($model as $data) {
     if($data->calendar_date == $i->calendar_date){
        echo "<tr><td>".$data->bed."</td><td>".$data->ptinfo->prename.$data->ptinfo->ptname."</td><td>".$data->ptinfo->age."</td><td>REGULAR DIET</td><td></td><td></td><td></td><td></td><td></td></tr>";
     }
 }
?>
</table>

<sethtmlpagefooter name="sum" value="on"/>
<htmlpagefooter name="sum">
<table>
    <tr>
    <td width="44%">
    <table calss="table_bordered" width="100%" border="1" cellpadding="2" cellspacing="0">
        <tr>
            <th>ชนิดอาหาร</th>
            <th>พิเศษ</th>
            <th>50/ที่</th>
            <th>สามัญ</th>
            <th>31/ที่</th>
        </tr>
        <tr>
            <td>อาหารธรรมดา</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>อาหารเฉพาะโรค</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>อาหารเหลวทั่วไป</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>อาหารปั่นทางสายยาง</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>อาหารอื่น</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>รวม</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </table>
</td>
<td>
    ผู้สั่งอาหาร &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; (หัวหน้าเวรหรือผู้ด้รับมอบหมาย) <br>
    <br>
    ผู้รับทำอาหาร
    <br>&emsp;&emsp;&emsp;&emsp;(นายชาญณรงค์  เหง้าเกษ)<br><br>
    กำหนดส่งมอบอาหารภายในเวลา &emsp;&emsp;&emsp;&emsp; น. ของวันที่ <?= $i->getDateorder() ?>
    <br>
    และผู้ตรวจรับได้ทำการตรวจสอบครบถ้วนถูกต้องแล้วจึงได้ลงชื่อไว้เป็นหลักฐาน<br>
    <br>
    ผู้ตรวจรับอาหาร&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;หัวหน้าเวร<br>    
</td>
</tr>
</table>
<br>
เรียนผู้ว่าราชการจังหวัดอุบลราชธานี<br>
&emsp;เพื่อทราบ&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;เจ้าหน้าที่<br>
&emsp;&emsp;&emsp;(&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;)&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;ทราบ<br>
<br>
&emsp;ทราบ&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;หัวหน้าเจ้าหน้าที่<br>
&emsp;&emsp;&emsp;(นางพัชรา  เดชาวัตร)
</htmlpagefooter>
<pagebreak>

</pagebreak>
<?php
}
?>

views/ipd/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Ipt */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="ipt-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'vn')->textInput() ?>

    <?= $form->field($model, 'an')->textInput() ?>

    <?= $form->field($model, 'hn')->textInput() ?>

    <?= $form->field($model, 'rgtdate')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/ipd/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\IptSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="ipt-search">

    <?php $form = ActiveForm::begin([
        'action' => ['dc'],
        'method' => 'get',
    ]); ?>
<div class="row">
<div class="col-md-3">
<?= $form->field($model, 'hn') ?>
</div>
<div class="col-md-3">
<?= $form->field($model, 'an') ?>
</div>
</div>


    <div class="form-group">
        <?= Html::submitButton('ค้นหา', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/ipd/_search_admit.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\IptSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="ipt-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>
<div class="row">
<div class="col-md-3">
<?= $form->field($model, 'hn') ?>
</div>
<div class="col-md-3">
<?= $form->field($model, 'an') ?>
</div>
</div>


    <div class="form-group">
        <?= Html::submitButton('ค้นหา', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/ipd/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Ipt */

$this->title = 'Create Ipt';
$this->params['breadcrumbs'][] = ['label' => 'Ipts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ipt-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/ipd/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\IptSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'ทะเบียนผู้ป่วยรับรักษา';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ipt-index">

    <?php echo $this->render('_search_admit', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        // 'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'vn',
            'an',
            'hn',
            'cid',
            'ptname',
            //'rgtdate',
            //'rgttime:datetime',
            //'pttype',
            //'prediag',
            //'dchdate',
            //'daycnt',
            //'dchtime:datetime',
            //'dchstts',
            //'dchtype',
            //'dthdiagdct',
            //'ipdlct',
            //'bmi',
            //'bw',
            //'height',
            //'tt',
            //'rr',
            //'pr',
            //'sbp',
            //'dbp',
            //'ipttype',
            //'painscore',
            //'symptmi',
            //'drg',
            //'rw',
            //'adjrw',
            //'error',
            //'warning',
            //'actlos',
            //'grouper_version',
            //'wtlos',
            //'ot',

            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'buttonOptions'=>['class'=>'btn btn-primary'],
                'template'=>'{print}',
                'buttons'=>[
                    'print' => function($url,$model,$key){
                      return Html::a('Print',['ipd/print','id'=>$model->an],['class' => 'btn btn-primary','target'=>'_blank']);
                    }
                ]
             ],
        ],
    ]); ?>


</div>

views/ipd/index_dc.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\IptSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'ทะเบียนจำหน่ายผู้ป่วย';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ipt-index">

    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        // 'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'vn',
            'an',
            'hn',
            'ptname',
            //'rgtdate',
            //'rgttime:datetime',
            //'pttype',
            //'prediag',
            //'dchdate',
            //'daycnt',
            //'dchtime:datetime',
            //'dchstts',
            //'dchtype',
            //'dthdiagdct',
            //'ipdlct',
            //'bmi',
            //'bw',
            //'height',
            //'tt',
            //'rr',
            //'pr',
            //'sbp',
            //'dbp',
            //'ipttype',
            //'painscore',
            //'symptmi',
            //'drg',
            //'rw',
            //'adjrw',
            //'error',
            //'warning',
            //'actlos',
            //'grouper_version',
            //'wtlos',
            //'ot',

            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'buttonOptions'=>['class'=>'btn btn-primary'],
                'template'=>'{print}',
                'buttons'=>[
                    'print' => function($url,$model,$key){
                      return Html::a('Print',['ipd/dcprint','id'=>$model->an],['class' => 'btn btn-primary','target'=>'_blank']);
                    }
                ]
             ],
        ],
    ]); ?>


</div>

views/ipd/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Ipt */

$this->title = 'Update Ipt: ' . $model->an;
$this->params['breadcrumbs'][] = ['label' => 'Ipts', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->an, 'url' => ['view', 'id' => $model->an]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="ipt-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/ipd/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\ListIpd */

$this->title = $model->an;
$this->params['breadcrumbs'][] = ['label' => 'List Ipds', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="list-ipd-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Print', ['print', 'id' => $model->an], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Print Summary', ['dcprint', 'id' => $model->an], ['class' => 'btn btn-primary']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'an',
            'hn',
            'prename',
            'ptname',
            'age',
            'cc',
            'pi:ntext',
            'ph:ntext',
            'pe:ntext',
            'bw',
            'tt',
            'sbp',
            'dbp',
            'pr',
            'rr',
            'height',
            'bmi',
            'prediag:ntext',
            'doctor',
            'lcno',
        ],
    ]) ?>

</div>